version: '3.8'

services:
  backend:
    build: ./Calculator
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mariadb;Database=mydatabase;User=myuser;Password=mypassword;
    depends_on:
      - mariadb
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - mariadb
    volumes:
      - ./db/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/mydatabase
      FLYWAY_USER: myuser
      FLYWAY_PASSWORD: mypassword
    command: migrate
    networks:
      - app_network

  k6:
    image: grafana/k6
    depends_on:
      - backend
    volumes:
      - ./k6:/scripts
    command: ["run", "/scripts/load_test.js"]
    networks:
      - app_network

  testcafe:
    image: testcafe/testcafe
    depends_on:
      - frontend
    volumes:
      - ./e2e:/tests
    command: ["chromium", "/tests/e2e_test.js"]
    networks:
      - app_network

  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - app_network

volumes:
  mariadb_data:

networks:
  app_network:
